---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# BEGIN
rsa:
  private-key: certs/private.pem
  public-key: certs/public.pem
# END